### ISSUE TITLE
Version 2 of Thoth.Json

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Thoth#36]
Issue to track what will be done for v2.

Most of the works has been made into separate branch/PR. I am merging all the works and discussion into a single branch called v2 :)

- [x] Improve message error by adding the jsonPath where the error failed [feature/track_path](https://github.com/MangelMaxime/Thoth/tree/feature/track_path)
- [x] Support Fable 2 #30 
- [x] Add auto encoder/decoder #30 
- [x] Remove pipeline style
- [x] Add object builder pattern #34 
- [x] Reduce exception usage when possible and don't match all the exception #34 
- [ ] ~~Rework the exposed API to the user `Json.parse -> Result<'T, string>` & `Json.parseOrRaise -> 'T`~~

**Bonus**

- [ ] Explore, if we can use a record/tuple instead of passing 2 arguments to decoder for the path tracking. Because this generate a lot of curry/uncurry function
- [ ] Try to reduce usage of unwrap, in the core library.

**Comment by MangelMaxime** [comment]
Both bonus point will not be implemented for Thoth.Json v2 release.

We are now focusing on releasing a stable version of the library. If this is needed we can still later deliver a new major/medium release.
